/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.fror.projecteuler.problem;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
 * starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find
 * the sum of the even-valued terms.
 */
public class Problem2 extends AbstractProblem {

  @Override
  public Object solve() {
    final int N = 4000000;

    int sum = 0;

    for (int a = 1, b = 2, tmp; b <= N; tmp = a + b, a = b, b = tmp) {
      if ((b & 1) == 0) {
        sum += b;
      }
    }
    return sum;
  }

}
